version: "3.7"
services:
  service1:
    build:
      args: 
          user: service1
          uid: 1000
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    ports:
      - 8881:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
